site_name: Developer Notes
nav:
  - index.md
  - AI, ML and Agents:
    - Frameworks: projects/project_a_more.md
    - Hosting: projects/project_b.md
    - ml/loss_functions.md
  - Python:
    - Syntax extentions: python/syntax_extensions.md

extra_javascript:
  - path: https://www.googletagmanager.com/gtag/js?id=G-733NHS8MJJ
    type: text/javascript
    async: true # Or false
  - path: javascripts/g.js
    type: text/javascript
    async: false
extra:
  extrahead:
    - |
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-733NHS8MJJ"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() {
          dataLayer.push(arguments);
        }
        gtag("js", new Date());
        gtag("config", "G-733NHS8MJJ");
      </script>
