site_name: Developer Notes
nav:
  - index.md
  - AI, ML and Agents:
    - Frameworks: projects/project_a_more.md
    - Hosting: projects/project_b.md
    - ml/loss_functions.md
    - agents/topics.md
  - Python:
    - Syntax extentions: python/syntax_extensions.md
theme:
  name: mkdocs
  custom_dir: templates
# templates_dir: templates
