site_name: Developer Notes
nav:
  - index.md
  - AI, ML and Agents:
    - a/ml/loss_functions.md
    - a/agents/topics.md
    - a/llm/vllm.md
  - Python:
    - Syntax extentions: a/python/syntax_extensions.md
    - Pydantic: a/python/pydantic.md
theme:
  name: mkdocs
  custom_dir: templates
# templates_dir: templates
